aws_region = "us-east-1"
instance_type_master = "t2.micro"
instance_type_node = "t2.micro"
ami = "ami-07761f3ae34c4478d"
key_name = "jenkins-new"
jenkins_agent_secret = "your_agent_secret_here"
private_key_path = "/path/to/your/private/key.pem"
